# Generated by Django 3.1.7 on 2022-10-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0003_auto_20221006_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pick',
            field=models.BooleanField(default=False),
        ),
    ]
