# Generated by Django 3.1.7 on 2022-10-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('comedy', '코미디'), ('horor', '호러'), ('fantasy', '판타지')], max_length=30),
        ),
    ]
