# Generated by Django 3.2.7 on 2022-10-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20221013_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tagging',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
